
# GENERATED BY ARCHIE
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

import os

class Config:
    """Base configuration."""
    SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-change-in-production")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    JWT_SECRET_KEY = os.environ.get("JWT_SECRET", "dev-jwt-secret-change-in-production")
    JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", "HS256")
    JWT_ACCESS_TOKEN_EXPIRES_HOURS = int(os.environ.get("ACCESS_TOKEN_EXPIRE_HOURS", "24"))
    CORS_ORIGINS = [
        o.strip()
        for o in os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:5173").split(",")
        if o.strip()
    ]

    @staticmethod
    def _db_url():
        raw = os.environ.get("DATABASE_URL", "sqlite:///./app.db")
        # Normalise Heroku-style postgres:// → postgresql://
        if raw.startswith("postgres://"):
            return raw.replace("postgres://", "postgresql://", 1)
        return raw

    SQLALCHEMY_DATABASE_URI = _db_url.__func__()

class DevelopmentConfig(Config):
    DEBUG = True
    SQLALCHEMY_ECHO = False

class ProductionConfig(Config):
    DEBUG = False
    SQLALCHEMY_POOL_SIZE = int(os.environ.get("DB_POOL_SIZE", "20"))
    SQLALCHEMY_MAX_OVERFLOW = int(os.environ.get("DB_MAX_OVERFLOW", "10"))
    SQLALCHEMY_POOL_RECYCLE = int(os.environ.get("DB_POOL_RECYCLE", "3600"))
    SQLALCHEMY_POOL_PRE_PING = True

class TestingConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = os.environ.get("TEST_DATABASE_URL", "sqlite:///:memory:")
    WTF_CSRF_ENABLED = False

_config_map = {
    "development": DevelopmentConfig,
    "production": ProductionConfig,
    "testing": TestingConfig,
}

def get_config():
    env = os.environ.get("ENV", "development")
    return _config_map.get(env, DevelopmentConfig)
