




# GENERATED BY ARCHIE
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z

PROJECT  := archiet-ai-native-architecture-to-code-saas-platform
IMAGE    := archiet-ai-native-architecture-to-code-saas-platform
ENV      ?= staging

.PHONY: dev mock test test-behavioral test-edge-cases test-security test-load test-all lint db-migrate db-seed infra-plan infra-apply deploy-staging deploy-prod clean

# ── Local Development ──────────────────────────────────────────────────────

dev:
	docker compose up -d --build
	@echo ""
	@echo "  $(PROJECT) is running"
	@echo "  App:     http://localhost:5000"

	@echo "  Health:  http://localhost:5000/health"

# ── Mock Server (zero dependencies) ──────────────────────────────────────

mock:
	python mock_server.py --port 5000
	@echo "Mock server: http://localhost:5000"

# ── Testing ────────────────────────────────────────────────────────────────

test:
	docker compose run --rm app pytest tests/ -v

test-behavioral:

	docker compose run --rm app go test -run TestBehavioral -v ./...


test-edge-cases:

	docker compose run --rm app go test -run TestEdgeCase -v ./...


test-security:

	docker compose run --rm app go test -run "TestSecurity|TestCORS|TestRateLimit|TestInjection|TestAuth" -v ./...


test-load:
	k6 run tests/k6_load_test.js --env BASE_URL=http://localhost:5000

test-all: test test-behavioral test-edge-cases test-security

lint:
	docker compose run --rm app ruff check .

# ── Database ───────────────────────────────────────────────────────────────

db-migrate:
	docker compose run --rm app flask db upgrade

db-seed:
	docker compose run --rm app 

# ── Infrastructure (requires Terraform + cloud credentials) ───────────────

infra-plan:
	cd terraform && terraform init && terraform plan -var="environment=$(ENV)"

infra-apply:
	cd terraform && terraform init && terraform apply -auto-approve -var="environment=$(ENV)"

# ── Deploy ─────────────────────────────────────────────────────────────────

deploy-staging:
	kubectl apply -f k8s/ -n archiet-ai-native-architecture-to-code-saas-platform-staging
	kubectl rollout status deployment/$(PROJECT) -n archiet-ai-native-architecture-to-code-saas-platform-staging --timeout=120s

deploy-prod:
	kubectl apply -f k8s/ -n archiet-ai-native-architecture-to-code-saas-platform-prod
	kubectl rollout status deployment/$(PROJECT) -n archiet-ai-native-architecture-to-code-saas-platform-prod --timeout=120s

# ── Cleanup ────────────────────────────────────────────────────────────────

clean:
	docker compose down -v
	docker rmi $(IMAGE) 2>/dev/null || true
