
# GENERATED BY ARCHIE
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE
#
# Run locally:  flask run --port 5000
# Run in prod:  gunicorn -c gunicorn.conf.py wsgi:app

from app import create_app

app = create_app()

if __name__ == "__main__":
    app.run()
