"""Test configuration — generated by A.R.C.H.I.E. Code Workbench (Flask).

Provides a synchronous SQLite test database so pytest runs without PostgreSQL.
Uses Flask's built-in test client.
"""
import os

# Must be set before any app imports so SQLAlchemy uses SQLite, not Postgres.
os.environ["DATABASE_URL"] = "sqlite:///./test.db"
os.environ["TESTING"] = "1"
os.environ.setdefault("SECRET_KEY", "test-secret-not-for-production")
os.environ.setdefault("JWT_SECRET", "test-jwt-not-for-production")

import pytest

# ── Dynamic imports — LLM may place app/Base at different paths ──────────────

def _try_import_app():
    for mod_path, attr in [
        ("app", "create_app"),
        ("app.app", "create_app"),
        ("wsgi", "app"),
    ]:
        try:
            mod = __import__(mod_path, fromlist=[attr])
            obj = getattr(mod, attr, None)
            if obj is not None:
                return obj
        except Exception:
            pass
    return None

def _try_import_db():
    for mod_path, attr in [
        ("app.extensions", "db"),
        ("app.db", "db"),
        ("app", "db"),
    ]:
        try:
            mod = __import__(mod_path, fromlist=[attr])
            obj = getattr(mod, attr, None)
            if obj is not None:
                return obj
        except Exception:
            pass
    return None

_create_app = _try_import_app()
_db = _try_import_db()

# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture(scope="session")
def app():
    """Create Flask app configured for testing."""
    if _create_app is None:
        pytest.skip("Flask app factory not importable")
    if callable(_create_app):
        application = _create_app()
    else:
        application = _create_app
    application.config["TESTING"] = True
    application.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///:memory:"
    return application

@pytest.fixture(scope="session")
def db_tables(app):
    """Create all tables once for the whole test session, then drop them."""
    if _db is not None:
        with app.app_context():
            try:
                _db.create_all()
            except Exception as exc:
                pytest.skip(f"DB table creation failed: {exc}")
    yield
    if _db is not None:
        with app.app_context():
            try:
                _db.drop_all()
            except Exception:
                pass

@pytest.fixture
def client(app, db_tables):
    """Flask test client."""
    with app.test_client() as c:
        with app.app_context():
            yield c
