
# GENERATED BY ARCHIE — tests for workspace
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

"""
Integration tests for workspace CRUD endpoints.
Uses Flask test_client — no network required.
"""
from __future__ import annotations

import json
import pytest

@pytest.fixture(scope="module")
def app():
    """Create a test Flask application with an in-memory DB."""
    from app import create_app
    from config import TestingConfig

    flask_app = create_app(TestingConfig)
    with flask_app.app_context():
        from database import db
        db.create_all()
        yield flask_app
        db.drop_all()

@pytest.fixture(scope="module")
def client(app):
    return app.test_client()

@pytest.fixture(scope="module")
def auth_headers(client):
    """Obtain a JWT token for the test user."""
    resp = client.post(
        "/auth/login",
        data=json.dumps({"username": "testuser", "sub": "testuser"}),
        content_type="application/json",
    )
    token = resp.get_json().get("access_token", "")
    return {"Authorization": f"Bearer {token}"}

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

BASE_URL = "/api/workspaces"

_SAMPLE_PAYLOAD: dict = {

    "name": "test-value-1",

    "description": "test-value-2",

    "status": "sample-3",

    "created_at": "sample-4",

    "updated_at": "sample-5",

}

# ---------------------------------------------------------------------------
# CRUD tests
# ---------------------------------------------------------------------------

def test_create_workspace(client, auth_headers):
    resp = client.post(
        f"{BASE_URL}/",
        data=json.dumps(_SAMPLE_PAYLOAD),
        content_type="application/json",
        headers=auth_headers,
    )
    assert resp.status_code == 201
    body = resp.get_json()
    assert "id" in body
    pytest._workspace_id = body["id"]

def test_list_workspaces(client, auth_headers):
    resp = client.get(f"{BASE_URL}/", headers=auth_headers)
    assert resp.status_code == 200
    body = resp.get_json()
    assert "items" in body
    assert isinstance(body["items"], list)

def test_get_workspace(client, auth_headers):
    # Create first
    create_resp = client.post(
        f"{BASE_URL}/",
        data=json.dumps(_SAMPLE_PAYLOAD),
        content_type="application/json",
        headers=auth_headers,
    )
    item_id = create_resp.get_json()["id"]

    resp = client.get(f"{BASE_URL}/{item_id}", headers=auth_headers)
    assert resp.status_code == 200
    assert resp.get_json()["id"] == item_id

def test_update_workspace(client, auth_headers):
    create_resp = client.post(
        f"{BASE_URL}/",
        data=json.dumps(_SAMPLE_PAYLOAD),
        content_type="application/json",
        headers=auth_headers,
    )
    item_id = create_resp.get_json()["id"]

    update_payload = dict(_SAMPLE_PAYLOAD)

    update_payload["name"] = "updated-value"

    resp = client.put(
        f"{BASE_URL}/{item_id}",
        data=json.dumps(update_payload),
        content_type="application/json",
        headers=auth_headers,
    )
    assert resp.status_code == 200

def test_delete_workspace(client, auth_headers):
    create_resp = client.post(
        f"{BASE_URL}/",
        data=json.dumps(_SAMPLE_PAYLOAD),
        content_type="application/json",
        headers=auth_headers,
    )
    item_id = create_resp.get_json()["id"]

    resp = client.delete(f"{BASE_URL}/{item_id}", headers=auth_headers)
    assert resp.status_code == 204

    get_resp = client.get(f"{BASE_URL}/{item_id}", headers=auth_headers)
    assert get_resp.status_code == 404

def test_list_pagination(client, auth_headers):
    resp = client.get(f"{BASE_URL}/?page=1&per_page=5", headers=auth_headers)
    assert resp.status_code == 200
    body = resp.get_json()
    assert "total" in body
    assert "pages" in body

def test_unauthenticated_returns_401(client):
    resp = client.get(f"{BASE_URL}/")
    assert resp.status_code == 401
