# GENERATED BY ARCHIE
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# generated_at: 2026-04-06T18-28-31Z
#
# Terraform configuration for Archiet — AI-Native Architecture-to-Code SaaS Platform database provisioning.
# State backend is NOT configured — teams choose their own (S3, GCS, etc.).

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      ManagedBy  = "terraform"
      Source     = "archie-codegen"
      SolutionId = "5373"
    }
  }
}
