# GENERATED BY ARCHIE
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
#
# AWS RDS PostgreSQL instance for Archiet — AI-Native Architecture-to-Code SaaS Platform.
# Credentials come from Terraform variables — never hardcoded.

locals {
  project_name = "archiet-ai-native-architecture-to-code-saas-platform"
  db_name      = "archiet_ai_native_architecture_to_code_saas_platform"
}

# ── Security Group ──────────────────────────────────────────────────────────

resource "aws_security_group" "db" {
  name_prefix = "${local.project_name}-db-"
  description = "Security group for ${local.project_name} RDS instance"
  vpc_id      = var.vpc_id

  ingress {
    description = "PostgreSQL from allowed CIDRs"
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = var.allowed_cidr_blocks
  }

  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "${local.project_name}-db-sg"
    Environment = var.environment
  }

  lifecycle {
    create_before_destroy = true
  }
}

# ── Subnet Group ────────────────────────────────────────────────────────────

resource "aws_db_subnet_group" "main" {
  name       = "${local.project_name}-${var.environment}"
  subnet_ids = var.private_subnet_ids

  tags = {
    Name        = "${local.project_name}-db-subnet-group"
    Environment = var.environment
  }
}

# ── Parameter Group ─────────────────────────────────────────────────────────

resource "aws_db_parameter_group" "main" {
  name_prefix = "${local.project_name}-pg16-"
  family      = "postgres0"
  description = "Parameter group for ${local.project_name}"

  parameter {
    name  = "log_connections"
    value = "1"
  }

  parameter {
    name  = "log_disconnections"
    value = "1"
  }

  parameter {
    name  = "log_statement"
    value = "ddl"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = {
    Environment = var.environment
  }
}

# ── RDS Instance ────────────────────────────────────────────────────────────

resource "aws_db_instance" "main" {
  identifier     = "${local.project_name}-${var.environment}"
  engine         = "postgres"
  engine_version = "0"
  instance_class = var.db_instance_class

  allocated_storage     = var.db_allocated_storage
  max_allocated_storage = var.db_max_allocated_storage
  storage_type          = "gp3"

  db_name  = local.db_name
  username = var.db_username
  password = var.db_password

  multi_az               = false
  storage_encrypted      = true
  backup_retention_period = 7

  vpc_security_group_ids = [aws_security_group.db.id]
  db_subnet_group_name   = aws_db_subnet_group.main.name
  parameter_group_name   = aws_db_parameter_group.main.name

  skip_final_snapshot       = var.environment != "production"
  final_snapshot_identifier = var.environment == "production" ? "${local.project_name}-final-snapshot" : null
  deletion_protection       = var.environment == "production"

  performance_insights_enabled = var.environment == "production"

  tags = {
    Name        = "${local.project_name}-${var.environment}"
    Environment = var.environment
    ManagedBy   = "terraform"
    Source      = "archie-codegen"
    SolutionId  = "5373"
  }
}
