
# GENERATED BY ARCHIE — entity: activedirectoryad
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class ActivedirectoryadSchema(Schema):
    """Marshmallow serialization/validation schema for activedirectoryad."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class ActivedirectoryadCreateSchema(ActivedirectoryadSchema):
    """Schema for POST /activedirectoryads — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class ActivedirectoryadUpdateSchema(Schema):
    """Schema for PUT /activedirectoryads/<id> — all fields optional."""
