
# GENERATED BY ARCHIE — entity: aiarchitectureengine
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class AiarchitectureengineSchema(Schema):
    """Marshmallow serialization/validation schema for aiarchitectureengine."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class AiarchitectureengineCreateSchema(AiarchitectureengineSchema):
    """Schema for POST /aiarchitectureengines — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class AiarchitectureengineUpdateSchema(Schema):
    """Schema for PUT /aiarchitectureengines/<id> — all fields optional."""
