
# GENERATED BY ARCHIE — entity: analyticsdatastore
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class AnalyticsdatastoreSchema(Schema):
    """Marshmallow serialization/validation schema for analyticsdatastore."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class AnalyticsdatastoreCreateSchema(AnalyticsdatastoreSchema):
    """Schema for POST /analyticsdatastores — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class AnalyticsdatastoreUpdateSchema(Schema):
    """Schema for PUT /analyticsdatastores/<id> — all fields optional."""
