
# GENERATED BY ARCHIE — entity: architecturetemplategallery
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class ArchitecturetemplategallerySchema(Schema):
    """Marshmallow serialization/validation schema for architecturetemplategallery."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class ArchitecturetemplategalleryCreateSchema(ArchitecturetemplategallerySchema):
    """Schema for POST /architecturetemplategallerys — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class ArchitecturetemplategalleryUpdateSchema(Schema):
    """Schema for PUT /architecturetemplategallerys/<id> — all fields optional."""
