
# GENERATED BY ARCHIE — entity: authenticationservice
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class AuthenticationserviceSchema(Schema):
    """Marshmallow serialization/validation schema for authenticationservice."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class AuthenticationserviceCreateSchema(AuthenticationserviceSchema):
    """Schema for POST /authenticationservices — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class AuthenticationserviceUpdateSchema(Schema):
    """Schema for PUT /authenticationservices/<id> — all fields optional."""
