
# GENERATED BY ARCHIE — entity: blueprintpublicviewer
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class BlueprintpublicviewerSchema(Schema):
    """Marshmallow serialization/validation schema for blueprintpublicviewer."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class BlueprintpublicviewerCreateSchema(BlueprintpublicviewerSchema):
    """Schema for POST /blueprintpublicviewers — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class BlueprintpublicviewerUpdateSchema(Schema):
    """Schema for PUT /blueprintpublicviewers/<id> — all fields optional."""
