
# GENERATED BY ARCHIE — entity: blueprintjourneyinterface
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class BlueprintjourneyinterfaceSchema(Schema):
    """Marshmallow serialization/validation schema for blueprintjourneyinterface."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class BlueprintjourneyinterfaceCreateSchema(BlueprintjourneyinterfaceSchema):
    """Schema for POST /blueprintjourneyinterfaces — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class BlueprintjourneyinterfaceUpdateSchema(Schema):
    """Schema for PUT /blueprintjourneyinterfaces/<id> — all fields optional."""
