
# GENERATED BY ARCHIE — entity: businesslogiclayer
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class BusinesslogiclayerSchema(Schema):
    """Marshmallow serialization/validation schema for businesslogiclayer."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class BusinesslogiclayerCreateSchema(BusinesslogiclayerSchema):
    """Schema for POST /businesslogiclayers — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class BusinesslogiclayerUpdateSchema(Schema):
    """Schema for PUT /businesslogiclayers/<id> — all fields optional."""
