
# GENERATED BY ARCHIE — entity: cicdpipeline
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class CicdpipelineSchema(Schema):
    """Marshmallow serialization/validation schema for cicdpipeline."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class CicdpipelineCreateSchema(CicdpipelineSchema):
    """Schema for POST /cicdpipelines — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class CicdpipelineUpdateSchema(Schema):
    """Schema for PUT /cicdpipelines/<id> — all fields optional."""
