
# GENERATED BY ARCHIE — entity: cicdtoolchain
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class CicdtoolchainSchema(Schema):
    """Marshmallow serialization/validation schema for cicdtoolchain."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class CicdtoolchainCreateSchema(CicdtoolchainSchema):
    """Schema for POST /cicdtoolchains — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class CicdtoolchainUpdateSchema(Schema):
    """Schema for PUT /cicdtoolchains/<id> — all fields optional."""
