
# GENERATED BY ARCHIE — entity: codegenerationservice
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class CodegenerationserviceSchema(Schema):
    """Marshmallow serialization/validation schema for codegenerationservice."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class CodegenerationserviceCreateSchema(CodegenerationserviceSchema):
    """Schema for POST /codegenerationservices — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class CodegenerationserviceUpdateSchema(Schema):
    """Schema for PUT /codegenerationservices/<id> — all fields optional."""
