
# GENERATED BY ARCHIE — entity: corebusinessfunction
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class CorebusinessfunctionSchema(Schema):
    """Marshmallow serialization/validation schema for corebusinessfunction."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class CorebusinessfunctionCreateSchema(CorebusinessfunctionSchema):
    """Schema for POST /corebusinessfunctions — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class CorebusinessfunctionUpdateSchema(Schema):
    """Schema for PUT /corebusinessfunctions/<id> — all fields optional."""
