
# GENERATED BY ARCHIE — entity: corebusiness
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class CorebusinessSchema(Schema):
    """Marshmallow serialization/validation schema for corebusiness."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class CorebusinessCreateSchema(CorebusinessSchema):
    """Schema for POST /corebusinesss — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class CorebusinessUpdateSchema(Schema):
    """Schema for PUT /corebusinesss/<id> — all fields optional."""
