
# GENERATED BY ARCHIE — entity: corebusinessapi
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class CorebusinessapiSchema(Schema):
    """Marshmallow serialization/validation schema for corebusinessapi."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class CorebusinessapiCreateSchema(CorebusinessapiSchema):
    """Schema for POST /corebusinessapis — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class CorebusinessapiUpdateSchema(Schema):
    """Schema for PUT /corebusinessapis/<id> — all fields optional."""
