
# GENERATED BY ARCHIE — entity: exportservice
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class ExportserviceSchema(Schema):
    """Marshmallow serialization/validation schema for exportservice."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class ExportserviceCreateSchema(ExportserviceSchema):
    """Schema for POST /exportservices — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class ExportserviceUpdateSchema(Schema):
    """Schema for PUT /exportservices/<id> — all fields optional."""
