
# GENERATED BY ARCHIE — entity: gdprcomplianceservice
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class GdprcomplianceserviceSchema(Schema):
    """Marshmallow serialization/validation schema for gdprcomplianceservice."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class GdprcomplianceserviceCreateSchema(GdprcomplianceserviceSchema):
    """Schema for POST /gdprcomplianceservices — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class GdprcomplianceserviceUpdateSchema(Schema):
    """Schema for PUT /gdprcomplianceservices/<id> — all fields optional."""
