
# GENERATED BY ARCHIE — entity: generatedcodeartifacts
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class GeneratedcodeartifactsSchema(Schema):
    """Marshmallow serialization/validation schema for generatedcodeartifacts."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class GeneratedcodeartifactsCreateSchema(GeneratedcodeartifactsSchema):
    """Schema for POST /generatedcodeartifactss — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class GeneratedcodeartifactsUpdateSchema(Schema):
    """Schema for PUT /generatedcodeartifactss/<id> — all fields optional."""
