
# GENERATED BY ARCHIE — entity: genomespecgenerator
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class GenomespecgeneratorSchema(Schema):
    """Marshmallow serialization/validation schema for genomespecgenerator."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class GenomespecgeneratorCreateSchema(GenomespecgeneratorSchema):
    """Schema for POST /genomespecgenerators — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class GenomespecgeneratorUpdateSchema(Schema):
    """Schema for PUT /genomespecgenerators/<id> — all fields optional."""
