
# GENERATED BY ARCHIE — entity: genomespecdefinitions
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class GenomespecdefinitionsSchema(Schema):
    """Marshmallow serialization/validation schema for genomespecdefinitions."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class GenomespecdefinitionsCreateSchema(GenomespecdefinitionsSchema):
    """Schema for POST /genomespecdefinitionss — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class GenomespecdefinitionsUpdateSchema(Schema):
    """Schema for PUT /genomespecdefinitionss/<id> — all fields optional."""
