
# GENERATED BY ARCHIE — entity: githubintegrationservice
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class GithubintegrationserviceSchema(Schema):
    """Marshmallow serialization/validation schema for githubintegrationservice."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class GithubintegrationserviceCreateSchema(GithubintegrationserviceSchema):
    """Schema for POST /githubintegrationservices — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class GithubintegrationserviceUpdateSchema(Schema):
    """Schema for PUT /githubintegrationservices/<id> — all fields optional."""
