
# GENERATED BY ARCHIE — entity: identityandaccessmanagement
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class IdentityandaccessmanagementSchema(Schema):
    """Marshmallow serialization/validation schema for identityandaccessmanagement."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class IdentityandaccessmanagementCreateSchema(IdentityandaccessmanagementSchema):
    """Schema for POST /identityandaccessmanagements — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class IdentityandaccessmanagementUpdateSchema(Schema):
    """Schema for PUT /identityandaccessmanagements/<id> — all fields optional."""
