
# GENERATED BY ARCHIE — entity: journeysessionorchestrator
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class JourneysessionorchestratorSchema(Schema):
    """Marshmallow serialization/validation schema for journeysessionorchestrator."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class JourneysessionorchestratorCreateSchema(JourneysessionorchestratorSchema):
    """Schema for POST /journeysessionorchestrators — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class JourneysessionorchestratorUpdateSchema(Schema):
    """Schema for PUT /journeysessionorchestrators/<id> — all fields optional."""
