
# GENERATED BY ARCHIE — entity: journeysessionconversations
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class JourneysessionconversationsSchema(Schema):
    """Marshmallow serialization/validation schema for journeysessionconversations."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class JourneysessionconversationsCreateSchema(JourneysessionconversationsSchema):
    """Schema for POST /journeysessionconversationss — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class JourneysessionconversationsUpdateSchema(Schema):
    """Schema for PUT /journeysessionconversationss/<id> — all fields optional."""
