
# GENERATED BY ARCHIE — entity: keymetricsandkpis
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class KeymetricsandkpisSchema(Schema):
    """Marshmallow serialization/validation schema for keymetricsandkpis."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class KeymetricsandkpisCreateSchema(KeymetricsandkpisSchema):
    """Schema for POST /keymetricsandkpiss — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class KeymetricsandkpisUpdateSchema(Schema):
    """Schema for PUT /keymetricsandkpiss/<id> — all fields optional."""
