
# GENERATED BY ARCHIE — entity: messagebroker
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class MessagebrokerSchema(Schema):
    """Marshmallow serialization/validation schema for messagebroker."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class MessagebrokerCreateSchema(MessagebrokerSchema):
    """Schema for POST /messagebrokers — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class MessagebrokerUpdateSchema(Schema):
    """Schema for PUT /messagebrokers/<id> — all fields optional."""
