
# GENERATED BY ARCHIE — entity: monitoringplatform
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class MonitoringplatformSchema(Schema):
    """Marshmallow serialization/validation schema for monitoringplatform."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class MonitoringplatformCreateSchema(MonitoringplatformSchema):
    """Schema for POST /monitoringplatforms — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class MonitoringplatformUpdateSchema(Schema):
    """Schema for PUT /monitoringplatforms/<id> — all fields optional."""
