
# GENERATED BY ARCHIE — entity: notificationservice
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class NotificationserviceSchema(Schema):
    """Marshmallow serialization/validation schema for notificationservice."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class NotificationserviceCreateSchema(NotificationserviceSchema):
    """Schema for POST /notificationservices — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class NotificationserviceUpdateSchema(Schema):
    """Schema for PUT /notificationservices/<id> — all fields optional."""
