
# GENERATED BY ARCHIE — entity: primarydatastore
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class PrimarydatastoreSchema(Schema):
    """Marshmallow serialization/validation schema for primarydatastore."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class PrimarydatastoreCreateSchema(PrimarydatastoreSchema):
    """Schema for POST /primarydatastores — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class PrimarydatastoreUpdateSchema(Schema):
    """Schema for PUT /primarydatastores/<id> — all fields optional."""
