
# GENERATED BY ARCHIE — entity: rowlevelsecurityenforcer
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class RowlevelsecurityenforcerSchema(Schema):
    """Marshmallow serialization/validation schema for rowlevelsecurityenforcer."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class RowlevelsecurityenforcerCreateSchema(RowlevelsecurityenforcerSchema):
    """Schema for POST /rowlevelsecurityenforcers — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class RowlevelsecurityenforcerUpdateSchema(Schema):
    """Schema for PUT /rowlevelsecurityenforcers/<id> — all fields optional."""
