
# GENERATED BY ARCHIE — entity: stripewebhookhandler
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class StripewebhookhandlerSchema(Schema):
    """Marshmallow serialization/validation schema for stripewebhookhandler."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

class StripewebhookhandlerCreateSchema(StripewebhookhandlerSchema):
    """Schema for POST /stripewebhookhandlers — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class StripewebhookhandlerUpdateSchema(Schema):
    """Schema for PUT /stripewebhookhandlers/<id> — all fields optional."""
