
# GENERATED BY ARCHIE — entity: workspace
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from marshmallow import Schema, fields, validate

class WorkspaceSchema(Schema):
    """Marshmallow serialization/validation schema for workspace."""

    id = fields.Str(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)

    name = fields.Str(required=True)

    description = fields.Str(load_default=None)

    status = fields.Str(required=True)

    created_at = fields.DateTime(load_default=None)

    updated_at = fields.DateTime(load_default=None)

class WorkspaceCreateSchema(WorkspaceSchema):
    """Schema for POST /workspaces — id/timestamps excluded."""
    id = fields.Str(load_only=True, load_default=None)

class WorkspaceUpdateSchema(Schema):
    """Schema for PUT /workspaces/<id> — all fields optional."""

    name = fields.Str(load_default=None)

    description = fields.Str(load_default=None)

    status = fields.Str(load_default=None)

    created_at = fields.DateTime(load_default=None, allow_none=True)

    updated_at = fields.DateTime(load_default=None, allow_none=True)
