"""Initial schema — generated by A.R.C.H.I.E. Code Workbench

Revision ID: 0001
Revises:
Create Date: 2026-04-06 18:28:33
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table('analyticsdatastore',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('line_1', sa.String(255), nullable=True),
        sa.Column('line_2', sa.String(255), nullable=True),
        sa.Column('city', sa.String(255), nullable=True),
        sa.Column('postcode', sa.String(255), nullable=True),
        sa.Column('country', sa.String(255), nullable=True),
        sa.Column('latitude', sa.String(255), nullable=True),
        sa.Column('longitude', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    op.create_table('corebusinessentity',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('core_business_entity_code', sa.String(255), nullable=True),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('description', sa.String(255), nullable=True),
        sa.Column('status', sa.String(255), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    op.create_table('generated_code_artifacts',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('event_type', sa.String(255), nullable=True),
        sa.Column('entity_type', sa.String(255), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('actor_id', sa.Integer(), nullable=True),
        sa.Column('before_state', sa.String(255), nullable=True),
        sa.Column('after_state', sa.String(255), nullable=True),
        sa.Column('ip_address', sa.String(255), nullable=True),
        sa.Column('occurred_at', sa.DateTime(), nullable=True),
    )
    op.create_table('genome_spec_definitions',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('genomespec_definitions_code', sa.String(255), nullable=True),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('description', sa.String(255), nullable=True),
        sa.Column('status', sa.String(255), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    op.create_table('journey_session_conversations',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('title', sa.String(255), nullable=True),
        sa.Column('file_path', sa.String(255), nullable=True),
        sa.Column('mime_type', sa.String(255), nullable=True),
        sa.Column('file_size_bytes', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('tags', sa.String(255), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    op.create_table('keymetricsand_kp_is',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('key_metrics_and_kpis_code', sa.String(255), nullable=True),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('description', sa.String(255), nullable=True),
        sa.Column('status', sa.String(255), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    op.create_table('workspace_data',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('workspace_data_code', sa.String(255), nullable=True),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('description', sa.String(255), nullable=True),
        sa.Column('status', sa.String(255), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )

def downgrade() -> None:
    op.drop_table('workspace_data')
    op.drop_table('keymetricsand_kp_is')
    op.drop_table('journey_session_conversations')
    op.drop_table('genome_spec_definitions')
    op.drop_table('generated_code_artifacts')
    op.drop_table('corebusinessentity')
    op.drop_table('analyticsdatastore')
