
# GENERATED BY ARCHIE
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE
#
# App factory pattern: create_app() → used by wsgi.py

import logging
import structlog

from flask import Flask
from flask_jwt_extended import JWTManager
from flask_cors import CORS

from config import get_config
from database import db, migrate

def create_app(config_override=None) -> Flask:
    """Application factory."""
    app = Flask(__name__)
    cfg = config_override or get_config()
    app.config.from_object(cfg)

    # Extensions
    db.init_app(app)
    migrate.init_app(app, db)
    jwt = JWTManager(app)  # noqa: F841
    CORS(app, origins=app.config.get("CORS_ORIGINS", ["*"]))

    # Structured logging
    structlog.configure(
        processors=[
            structlog.stdlib.add_log_level,
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.TimeStamper(fmt="iso"),
            structlog.processors.JSONRenderer(),
        ],
        wrapper_class=structlog.BoundLogger,
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
        cache_logger_on_first_use=True,
    )
    logging.basicConfig(level=logging.INFO)

    # Register blueprints
    with app.app_context():
        # Core models (creates tables if missing)
        import importlib
        importlib.import_module('app.models.entities')
        try:
            importlib.import_module('app.models.user')
        except ImportError:
            pass
        db.create_all()

        # Auth blueprint
        from app.blueprints.auth_bp import auth_bp
        app.register_blueprint(auth_bp, url_prefix="/auth")

        # Entity blueprints

        from app.blueprints.smtprelaygcp_bp import smtprelaygcp_bp
        app.register_blueprint(smtprelaygcp_bp, url_prefix="/api/smtprelaygcp")

        from app.blueprints.primarydatastore_bp import primarydatastore_bp
        app.register_blueprint(primarydatastore_bp, url_prefix="/api/primarydatastore")

        from app.blueprints.identityandaccessmanagement_bp import identityandaccessmanagement_bp
        app.register_blueprint(identityandaccessmanagement_bp, url_prefix="/api/identityandaccessmanagement")

        from app.blueprints.authenticationservice_bp import authenticationservice_bp
        app.register_blueprint(authenticationservice_bp, url_prefix="/api/authenticationservice")

        from app.blueprints.monitoringplatform_bp import monitoringplatform_bp
        app.register_blueprint(monitoringplatform_bp, url_prefix="/api/monitoringplatform")

        from app.blueprints.analyticsengine_bp import analyticsengine_bp
        app.register_blueprint(analyticsengine_bp, url_prefix="/api/analyticsengine")

        from app.blueprints.reportingservice_bp import reportingservice_bp
        app.register_blueprint(reportingservice_bp, url_prefix="/api/reportingservice")

        from app.blueprints.gcpcohesityforsystemsbackup_bp import gcpcohesityforsystemsbackup_bp
        app.register_blueprint(gcpcohesityforsystemsbackup_bp, url_prefix="/api/gcpcohesityforsystemsbackup")

        from app.blueprints.apigateway_bp import apigateway_bp
        app.register_blueprint(apigateway_bp, url_prefix="/api/apigateway")

        from app.blueprints.messagebroker_bp import messagebroker_bp
        app.register_blueprint(messagebroker_bp, url_prefix="/api/messagebroker")

        from app.blueprints.businesslogiclayer_bp import businesslogiclayer_bp
        app.register_blueprint(businesslogiclayer_bp, url_prefix="/api/businesslogiclayer")

        from app.blueprints.corebusinessfunction_bp import corebusinessfunction_bp
        app.register_blueprint(corebusinessfunction_bp, url_prefix="/api/corebusinessfunction")

        from app.blueprints.corebusinessapi_bp import corebusinessapi_bp
        app.register_blueprint(corebusinessapi_bp, url_prefix="/api/corebusinessapi")

        from app.blueprints.frontendapplication_bp import frontendapplication_bp
        app.register_blueprint(frontendapplication_bp, url_prefix="/api/frontendapplication")

        from app.blueprints.activedirectoryad_bp import activedirectoryad_bp
        app.register_blueprint(activedirectoryad_bp, url_prefix="/api/activedirectoryad")

        from app.blueprints.notificationservice_bp import notificationservice_bp
        app.register_blueprint(notificationservice_bp, url_prefix="/api/notificationservice")

        from app.blueprints.googlegeminimodels_bp import googlegeminimodels_bp
        app.register_blueprint(googlegeminimodels_bp, url_prefix="/api/googlegeminimodels")

        from app.blueprints.veritasnetbackupsaas_bp import veritasnetbackupsaas_bp
        app.register_blueprint(veritasnetbackupsaas_bp, url_prefix="/api/veritasnetbackupsaas")

        from app.blueprints.blueprintjourneyinterface_bp import blueprintjourneyinterface_bp
        app.register_blueprint(blueprintjourneyinterface_bp, url_prefix="/api/blueprintjourneyinterface")

        from app.blueprints.architecturetemplategallery_bp import architecturetemplategallery_bp
        app.register_blueprint(architecturetemplategallery_bp, url_prefix="/api/architecturetemplategallery")

        from app.blueprints.blueprintpublicviewer_bp import blueprintpublicviewer_bp
        app.register_blueprint(blueprintpublicviewer_bp, url_prefix="/api/blueprintpublicviewer")

        from app.blueprints.cicdtoolchain_bp import cicdtoolchain_bp
        app.register_blueprint(cicdtoolchain_bp, url_prefix="/api/cicdtoolchain")

        from app.blueprints.cicdpipeline_bp import cicdpipeline_bp
        app.register_blueprint(cicdpipeline_bp, url_prefix="/api/cicdpipeline")

        from app.blueprints.healthmonitoring_bp import healthmonitoring_bp
        app.register_blueprint(healthmonitoring_bp, url_prefix="/api/healthmonitoring")

        from app.blueprints.genomespecgenerator_bp import genomespecgenerator_bp
        app.register_blueprint(genomespecgenerator_bp, url_prefix="/api/genomespecgenerator")

        from app.blueprints.codegenerationservice_bp import codegenerationservice_bp
        app.register_blueprint(codegenerationservice_bp, url_prefix="/api/codegenerationservice")

        from app.blueprints.exportservice_bp import exportservice_bp
        app.register_blueprint(exportservice_bp, url_prefix="/api/exportservice")

        from app.blueprints.journeysessionorchestrator_bp import journeysessionorchestrator_bp
        app.register_blueprint(journeysessionorchestrator_bp, url_prefix="/api/journeysessionorchestrator")

        from app.blueprints.stripewebhookhandler_bp import stripewebhookhandler_bp
        app.register_blueprint(stripewebhookhandler_bp, url_prefix="/api/stripewebhookhandler")

        from app.blueprints.rowlevelsecurityenforcer_bp import rowlevelsecurityenforcer_bp
        app.register_blueprint(rowlevelsecurityenforcer_bp, url_prefix="/api/rowlevelsecurityenforcer")

        from app.blueprints.gdprcomplianceservice_bp import gdprcomplianceservice_bp
        app.register_blueprint(gdprcomplianceservice_bp, url_prefix="/api/gdprcomplianceservice")

        from app.blueprints.aiarchitectureengine_bp import aiarchitectureengine_bp
        app.register_blueprint(aiarchitectureengine_bp, url_prefix="/api/aiarchitectureengine")

        from app.blueprints.usagemeteringlimiting_bp import usagemeteringlimiting_bp
        app.register_blueprint(usagemeteringlimiting_bp, url_prefix="/api/usagemeteringlimiting")

        from app.blueprints.qualityscoringengine_bp import qualityscoringengine_bp
        app.register_blueprint(qualityscoringengine_bp, url_prefix="/api/qualityscoringengine")

        from app.blueprints.githubintegrationservice_bp import githubintegrationservice_bp
        app.register_blueprint(githubintegrationservice_bp, url_prefix="/api/githubintegrationservice")

        from app.blueprints.corebusiness_bp import corebusiness_bp
        app.register_blueprint(corebusiness_bp, url_prefix="/api/corebusiness")

        from app.blueprints.keymetricsandkpis_bp import keymetricsandkpis_bp
        app.register_blueprint(keymetricsandkpis_bp, url_prefix="/api/keymetricsandkpis")

        from app.blueprints.analyticsdatastore_bp import analyticsdatastore_bp
        app.register_blueprint(analyticsdatastore_bp, url_prefix="/api/analyticsdatastore")

        from app.blueprints.workspace_bp import workspace_bp
        app.register_blueprint(workspace_bp, url_prefix="/api/workspace")

        from app.blueprints.journeysessionconversations_bp import journeysessionconversations_bp
        app.register_blueprint(journeysessionconversations_bp, url_prefix="/api/journeysessionconversations")

        from app.blueprints.genomespecdefinitions_bp import genomespecdefinitions_bp
        app.register_blueprint(genomespecdefinitions_bp, url_prefix="/api/genomespecdefinitions")

        from app.blueprints.generatedcodeartifacts_bp import generatedcodeartifacts_bp
        app.register_blueprint(generatedcodeartifacts_bp, url_prefix="/api/generatedcodeartifacts")

        # Health probe
        @app.get("/health")
        def health():
            from flask import jsonify
            return jsonify({"status": "ok", "version": "code_2026-04-06T18-28-31Z"})


        # ── Engine blueprints (Journey Wizard + Codegen + Billing) ──────────
        from engine.routes.journey_bp import journey_bp
        app.register_blueprint(journey_bp)

        from engine.routes.codegen_bp import codegen_bp as codegen_engine_bp
        app.register_blueprint(codegen_engine_bp)

        from engine.routes.billing_bp import billing_bp
        app.register_blueprint(billing_bp)
        from engine.routes.settings_bp import settings_bp
        app.register_blueprint(settings_bp)
    return app
