/**
 * Accessibility tests — axe-core for WCAG 2.1 AA compliance.
 * Generated by A.R.C.H.I.E. DeterministicCodeGenerator
 */
import React from 'react';
import { render } from '@testing-library/react';
import { axe, toHaveNoViolations } from 'jest-axe';
import { rest } from 'msw';
import { setupServer } from 'msw/node';

import LoginPage from '@/app/(auth)/login/page';

expect.extend(toHaveNoViolations);

const BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
const server = setupServer(
  rest.get(`${BASE}/api/v1/`, (_req, res, ctx) =>
    res(ctx.json({ items: [], total: 0, page: 1, size: 20 }))
  )
);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

describe('Accessibility — WCAG 2.1 AA', () => {
  it('login page has no accessibility violations', async () => {
    const { container } = render(<LoginPage />);
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });



  it('login page form controls have visible labels', () => {
    const { getAllByRole } = render(<LoginPage />);
    const inputs = getAllByRole('textbox');
    inputs.forEach((input) => {
      expect(input).toHaveAccessibleName();
    });
  });


});
