/**
 * Component tests for Analyticsengine — covers render, interactions, API integration.
 * Generated by A.R.C.H.I.E. DeterministicCodeGenerator
 */
import React from 'react';
import { render, screen, fireEvent, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { rest } from 'msw';
import { setupServer } from 'msw/node';

import AnalyticsengineList from '@/app/analytics-engines/page';
import AnalyticsengineForm from '@/components/analytics-engines/AnalyticsengineForm';


// ---------------------------------------------------------------------------
// MSW mock server
// ---------------------------------------------------------------------------
const BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

const sampleAnalyticsengine = {
  id: '00000000-0000-0000-0000-000000000001',

  name: 'test-name',

  description: null,

  metric_name: 'test-metric_name',

  value: null,

  target: null,

  unit: 'test-unit',

  measured_at: null,

  status: null,

  created_at: null,

  updated_at: null,

};

const server = setupServer(
  rest.get(`${BASE}/api/v1/analytics-engines`, (_req, res, ctx) =>
    res(ctx.json({ items: [sampleAnalyticsengine], total: 1, page: 1, size: 20 }))
  ),
  rest.post(`${BASE}/api/v1/analytics-engines`, async (req, res, ctx) => {
    const body = await req.json();
    return res(ctx.json({ ...sampleAnalyticsengine, ...body, id: '00000000-0000-0000-0000-000000000002' }));
  }),
  rest.patch(`${BASE}/api/v1/analytics-engines/:id`, async (req, res, ctx) => {
    const body = await req.json();
    return res(ctx.json({ ...sampleAnalyticsengine, ...body }));
  }),
  rest.delete(`${BASE}/api/v1/analytics-engines/:id`, (_req, res, ctx) =>
    res(ctx.status(204))
  ),
);

beforeAll(() => server.listen({ onUnhandledRequest: 'warn' }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

// ---------------------------------------------------------------------------
// List page
// ---------------------------------------------------------------------------
describe('AnalyticsengineList page', () => {
  it('renders heading and fetches items on mount', async () => {
    render(<AnalyticsengineList />);
    expect(screen.getByRole('heading', { level: 1 })).toBeInTheDocument();
    await waitFor(() =>
      expect(screen.getByText('test-name')).toBeInTheDocument()
    );
  });

  it('shows empty state when no items returned', async () => {
    server.use(
      rest.get(`${BASE}/api/v1/analytics-engines`, (_req, res, ctx) =>
        res(ctx.json({ items: [], total: 0, page: 1, size: 20 }))
      )
    );
    render(<AnalyticsengineList />);
    await waitFor(() => expect(screen.getByText(/no analytics-engines/i)).toBeInTheDocument());
  });

  it('shows error message when API fails', async () => {
    server.use(
      rest.get(`${BASE}/api/v1/analytics-engines`, (_req, res, ctx) =>
        res(ctx.status(500), ctx.json({ detail: 'Internal server error' }))
      )
    );
    render(<AnalyticsengineList />);
    await waitFor(() => expect(screen.getByRole('alert')).toBeInTheDocument());
  });

  it('pagination controls update query', async () => {
    render(<AnalyticsengineList />);
    await screen.findByText('test-name');
    const nextBtn = screen.queryByRole('button', { name: /next/i });
    if (nextBtn) {
      await userEvent.click(nextBtn);
      // expect page param update (router mock captures push)
    }
  });
});

// ---------------------------------------------------------------------------
// Create form
// ---------------------------------------------------------------------------
describe('AnalyticsengineForm — create', () => {
  const onSuccess = jest.fn();

  beforeEach(() => onSuccess.mockClear());

  it('renders all required fields', () => {
    render(<AnalyticsengineForm onSuccess={onSuccess} />);


    expect(screen.getByLabelText(/name/i)).toBeInTheDocument();





    expect(screen.getByLabelText(/metric name/i)).toBeInTheDocument();



    expect(screen.getByLabelText(/value/i)).toBeInTheDocument();



    expect(screen.getByLabelText(/target/i)).toBeInTheDocument();



    expect(screen.getByLabelText(/unit/i)).toBeInTheDocument();



    expect(screen.getByLabelText(/measured at/i)).toBeInTheDocument();



    expect(screen.getByLabelText(/status/i)).toBeInTheDocument();






  });

  it('shows validation errors on empty submit', async () => {
    render(<AnalyticsengineForm onSuccess={onSuccess} />);
    await userEvent.click(screen.getByRole('button', { name: /save|create|submit/i }));
    await waitFor(() => {
      const alerts = screen.queryAllByRole('alert');
      expect(alerts.length).toBeGreaterThan(0);
    });
    expect(onSuccess).not.toHaveBeenCalled();
  });

  it('submits successfully with valid data and calls onSuccess', async () => {
    render(<AnalyticsengineForm onSuccess={onSuccess} />);


    await userEvent.type(screen.getByLabelText(/name/i), 'valid-name');





    await userEvent.type(screen.getByLabelText(/metric name/i), 'valid-metric_name');







    await userEvent.type(screen.getByLabelText(/unit/i), 'valid-unit');










    await userEvent.click(screen.getByRole('button', { name: /save|create|submit/i }));
    await waitFor(() => expect(onSuccess).toHaveBeenCalledTimes(1));
  });

  it('shows server error when API returns 422', async () => {
    server.use(
      rest.post(`${BASE}/api/v1/analytics-engines`, (_req, res, ctx) =>
        res(ctx.status(422), ctx.json({ detail: [{ loc: ['body', 'name'], msg: 'field required' }] }))
      )
    );
    render(<AnalyticsengineForm onSuccess={onSuccess} />);


    await userEvent.type(screen.getByLabelText(/name/i), 'x');





    await userEvent.type(screen.getByLabelText(/metric name/i), 'x');







    await userEvent.type(screen.getByLabelText(/unit/i), 'x');










    await userEvent.click(screen.getByRole('button', { name: /save|create|submit/i }));
    await waitFor(() => expect(screen.getByRole('alert')).toBeInTheDocument());
  });
});

// ---------------------------------------------------------------------------
// Edit form
// ---------------------------------------------------------------------------
describe('AnalyticsengineForm — edit', () => {
  const onSuccess = jest.fn();

  it('pre-fills fields with existing record values', () => {
    render(<AnalyticsengineForm initialData={sampleAnalyticsengine} onSuccess={onSuccess} />);


    expect(screen.getByDisplayValue('test-name')).toBeInTheDocument();





    expect(screen.getByDisplayValue('test-metric_name')).toBeInTheDocument();







    expect(screen.getByDisplayValue('test-unit')).toBeInTheDocument();










  });

  it('calls PATCH on submit and notifies onSuccess', async () => {
    render(<AnalyticsengineForm initialData={sampleAnalyticsengine} onSuccess={onSuccess} />);
    await userEvent.click(screen.getByRole('button', { name: /save|update/i }));
    await waitFor(() => expect(onSuccess).toHaveBeenCalledTimes(1));
  });
});

// ---------------------------------------------------------------------------
// Delete action
// ---------------------------------------------------------------------------
describe('Analyticsengine delete', () => {
  it('opens confirmation dialog before deleting', async () => {
    render(<AnalyticsengineList />);
    await screen.findByText('test-name');
    const deleteBtn = screen.getAllByRole('button', { name: /delete/i })[0];
    await userEvent.click(deleteBtn);
    expect(screen.getByRole('dialog')).toBeInTheDocument();
  });

  it('removes row from list after confirmed delete', async () => {
    render(<AnalyticsengineList />);
    await screen.findByText('test-name');
    const deleteBtn = screen.getAllByRole('button', { name: /delete/i })[0];
    await userEvent.click(deleteBtn);
    const dialog = screen.getByRole('dialog');
    await userEvent.click(within(dialog).getByRole('button', { name: /confirm|yes|delete/i }));
    await waitFor(() =>
      expect(screen.queryByText('test-name')).not.toBeInTheDocument()
    );
  });
});
