
# GENERATED BY ARCHIE
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from __future__ import annotations

import logging
from datetime import timedelta
from http import HTTPStatus

from flask import Blueprint, jsonify, request
from flask_jwt_extended import (
    create_access_token,
    get_jwt_identity,
    jwt_required,
)

logger = logging.getLogger(__name__)

auth_bp = Blueprint("auth", __name__)

# ---------------------------------------------------------------------------
# Local-auth routes  (login with username + password stored in User table)
# ---------------------------------------------------------------------------
from app.models.user import User  # noqa: E402

@auth_bp.route("/login", methods=["POST"])
def login():
    """Exchange username + password for a JWT access token."""
    body = request.get_json(force=True) or {}
    username = (body.get("username") or "").strip()
    password = body.get("password") or ""

    if not username or not password:
        return jsonify({"error": "username and password required"}), HTTPStatus.BAD_REQUEST

    user = User.query.filter_by(email=username).first() or User.query.filter_by(username=username).first()
    if user is None or not user.verify_password(password):
        return jsonify({"error": "invalid credentials"}), HTTPStatus.UNAUTHORIZED

    access_token = create_access_token(
        identity=str(user.id),
        expires_delta=timedelta(hours=24),
    )
    return jsonify({"access_token": access_token, "token_type": "bearer"})

@auth_bp.route("/me", methods=["GET"])
@jwt_required()
def me():
    """Return the current authenticated user's profile."""
    user_id = get_jwt_identity()
    user = User.query.get(user_id)
    if user is None:
        return jsonify({"error": "user not found"}), HTTPStatus.NOT_FOUND
    return jsonify(user.to_dict())
