
# GENERATED BY ARCHIE — entity: activedirectoryad
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from database import db

class Activedirectoryad(db.Model):
    """SQLAlchemy ORM model for activedirectoryad."""

    __tablename__ = "activedirectoryads"

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )

    def to_dict(self) -> dict[str, Any]:
        """Serialise to JSON-safe dict (used by blueprint jsonify calls)."""
        result: dict[str, Any] = {
            "id": self.id,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,

        }
        return result

    def __repr__(self) -> str:
        return f"<Activedirectoryad(id={self.id!r})>"
