
# GENERATED BY ARCHIE — entity: workspace
# solution_id: 5373
# bundle_id: code_2026-04-06T18-28-31Z
# DO NOT EDIT IN PLACE -- REGENERATE FROM ARCHITECTURE

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from database import db

class Workspace(db.Model):
    """SQLAlchemy ORM model for workspace."""

    __tablename__ = "workspaces"

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )

    name = db.Column(db.String(255), nullable=False)

    description = db.Column(db.Text, nullable=True)

    status = db.Column(db.Text, nullable=False)

    created_at = db.Column(db.DateTime, nullable=True)

    updated_at = db.Column(db.DateTime, nullable=True)

    def to_dict(self) -> dict[str, Any]:
        """Serialise to JSON-safe dict (used by blueprint jsonify calls)."""
        result: dict[str, Any] = {
            "id": self.id,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,

            "name": self.name,

            "description": self.description,

            "status": self.status,

            "created_at": self.created_at,

            "updated_at": self.updated_at,

        }
        return result

    def __repr__(self) -> str:
        return f"<Workspace(id={self.id!r})>"
