/**
 * E2E auth spec — full login/logout/redirect flows via Playwright.
 * Generated by A.R.C.H.I.E. DeterministicCodeGenerator
 */
import { test, expect } from '@playwright/test';

const VALID_EMAIL = process.env.E2E_USER_EMAIL || 'test@example.com';
const VALID_PASS  = process.env.E2E_USER_PASS  || 'Test@123!';

test.describe('Authentication flows', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/login');
  });

  test('login page renders correctly', async ({ page }) => {
    await expect(page).toHaveTitle(/Archiet — AI-Native Architecture-to-Code SaaS Platform/i);
    await expect(page.getByLabel(/email/i)).toBeVisible();
    await expect(page.getByLabel(/password/i)).toBeVisible();
    await expect(page.getByRole('button', { name: /sign in|log in/i })).toBeVisible();
  });

  test('redirects authenticated users away from login', async ({ page }) => {
    // Login first
    await page.getByLabel(/email/i).fill(VALID_EMAIL);
    await page.getByLabel(/password/i).fill(VALID_PASS);
    await page.getByRole('button', { name: /sign in|log in/i }).click();
    await page.waitForURL(url => !url.pathname.includes('login'));

    // Now try to go back to login
    await page.goto('/login');
    await expect(page).not.toHaveURL(/\/login/);
  });

  test('valid credentials → dashboard redirect', async ({ page }) => {
    await page.getByLabel(/email/i).fill(VALID_EMAIL);
    await page.getByLabel(/password/i).fill(VALID_PASS);
    await page.getByRole('button', { name: /sign in|log in/i }).click();
    await expect(page).not.toHaveURL(/\/login/);
    await expect(page.getByRole('navigation')).toBeVisible();
  });

  test('invalid credentials → error message', async ({ page }) => {
    await page.getByLabel(/email/i).fill(VALID_EMAIL);
    await page.getByLabel(/password/i).fill('WrongPassword!');
    await page.getByRole('button', { name: /sign in|log in/i }).click();
    await expect(page.getByRole('alert')).toContainText(/invalid|credentials|wrong/i);
    await expect(page).toHaveURL(/\/login/);
  });

  test('empty form submission shows field-level errors', async ({ page }) => {
    await page.getByRole('button', { name: /sign in|log in/i }).click();
    const errors = page.getByRole('alert');
    await expect(errors.first()).toBeVisible();
  });

  test('logout clears session and redirects to login', async ({ page }) => {
    // Login
    await page.getByLabel(/email/i).fill(VALID_EMAIL);
    await page.getByLabel(/password/i).fill(VALID_PASS);
    await page.getByRole('button', { name: /sign in|log in/i }).click();
    await page.waitForURL(url => !url.pathname.includes('login'));

    // Logout
    const logoutTrigger = page.getByRole('button', { name: /logout|sign out/i })
      .or(page.getByRole('menuitem', { name: /logout|sign out/i }));
    await logoutTrigger.click();
    await expect(page).toHaveURL(/\/login/);
  });

  test('protected route redirects unauthenticated user to login', async ({ page }) => {
    await page.goto('/dashboard');
    await expect(page).toHaveURL(/\/login/);
  });

  test('password field is masked', async ({ page }) => {
    const passwordInput = page.getByLabel(/password/i);
    await expect(passwordInput).toHaveAttribute('type', 'password');
  });

  test('no sensitive data leaked in page source after login', async ({ page }) => {
    await page.getByLabel(/email/i).fill(VALID_EMAIL);
    await page.getByLabel(/password/i).fill(VALID_PASS);
    await page.getByRole('button', { name: /sign in|log in/i }).click();
    await page.waitForURL(url => !url.pathname.includes('login'));
    const source = await page.content();
    expect(source).not.toContain(VALID_PASS);
  });
});
